# Supabase configuration
SUPABASE_URL = "https://rnqhongfxhavszyfibzr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJucWhvbmdmeGhhdnN6eWZpYnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODE3MjYsImV4cCI6MjA1NjI1NzcyNn0.UmwYVNEQ3IT1JUW7sK68p18RwQVYL_YVdbS57ihqmrE"

# API configuration
API_BASE_URL = "https://kaggle-api-back.onrender.com"

# Kaggle configuration
[kaggle]
KAGGLE_USERNAME = "oliveralmaguer"
KAGGLE_KEY = "3d893abb65e0cdee3b33bf70df6834e4"